/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "stm32f429i_discovery.h"
#include "ThinkGearStreamParser.h"
#include "stdbool.h"
#include "GUI.h"
#include "WIDGET.h"
#include "string.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_GRAPH_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_PROGBAR_0    (GUI_ID_USER + 0x05)
#define ID_PROGBAR_1    (GUI_ID_USER + 0x06)
#define ID_TEXT_1    (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_0    (GUI_ID_USER + 0x08)
#define ID_CHECKBOX_1    (GUI_ID_USER + 0x09)
#define ID_BUTTON_2    (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
WM_HWIN hgraph;
WM_HWIN hprog0;
WM_HWIN hprog1;
WM_HWIN chboxh0,chboxh1;
GRAPH_DATA_Handle hdata0;
GRAPH_DATA_Handle hdata1;
GRAPH_SCALE_Handle hscale;
bool start=false;
extern uint8_t recb;
extern uint8_t recb2;
extern UART_HandleTypeDef huart1,huart5;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window1", ID_WINDOW_0, 0, 0, 230, 290, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 14, 121, 200, 110, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Start", ID_BUTTON_0, 20, 253, 61, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Stop", ID_BUTTON_1, 150, 253, 55, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Attention", ID_TEXT_0, 91, 93, 51, 20, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 88, 28, 120, 20, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 88, 61, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Signal Quality", ID_TEXT_1, 111, 6, 72, 16, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 2, 28, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 2, 58, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CLR", ID_BUTTON_2, 100, 253, 38, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 30, 5, 5, 5);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Headset 1");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "Headset 2");
    // USER START (Optionally insert additional code for further widget initialization)
       hprog0=WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
       hprog1=WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
       PROGBAR_SetMinMax(hprog0,0,200);
       PROGBAR_SetMinMax(hprog1,0,200);
       hgraph = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
       GRAPH_SetGridDistX(hgraph,10);
       GRAPH_SetGridDistY(hgraph,10);
       hdata0=GRAPH_DATA_YT_Create(GUI_YELLOW,160,NULL,0);
       hdata1=GRAPH_DATA_YT_Create(GUI_RED,160,NULL,0);
       GRAPH_AttachData(hgraph,hdata0);
       GRAPH_AttachData(hgraph,hdata1);
       hscale=GRAPH_SCALE_Create(20,GUI_TA_HCENTER,GRAPH_SCALE_CF_VERTICAL,10);
       GRAPH_AttachScale(hgraph,hscale);
       GRAPH_SetGridVis(hgraph,10);
       GRAPH_DATA_YT_SetAlign(hdata0,GRAPH_ALIGN_LEFT);
       GRAPH_DATA_YT_SetAlign(hdata1,GRAPH_ALIGN_LEFT);
       chboxh0=WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
       chboxh1=WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  BSP_LED_On(LED4);
    	  start=true;

    //	  HAL_UART_Receive_IT(&huart5,&recb,1);
    //	  HAL_UART_Receive_IT(&huart1,&recb2,1);
    	//  setPWM(htim2,TIM_CHANNEL_1,300);
    	 // setPWM(htim2,TIM_CHANNEL_2,500);
    	        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Stop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'CLR'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow1
*/
WM_HWIN CreateWindow1(void);
WM_HWIN CreateWindow1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
